### ISSUE TITLE
Possible bug in migration tool: executeGraphQL yields a "cannot read property 'headers' of null"

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/graphql-server#90]
When using our new migration method `executeGraphQL` the above error is generated.

Possibly the GraphQL context holding `null` for the `request` attribute is the cause?

Please write integration tests, reproducing this error and fix the tests. 

Make sure all method of migration work, please

**Comment by coeit** [comment]
Error:
```
{
  "data": {
    "countAssays": null
  },
  "errors": [
    {
      "message": "Cannot read property 'headers' of null",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ],
      "path": [
        "countAssays"
      ]
    }
  ]
}
```
